name: SamsungTVPlus Auto Playlist

on:
  schedule:
    - cron: '30 4 */7 * *'  # Every 7 days at 10:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run SamsungTVPlus Script
      run: python samsungtvplus.py

    - name: Commit and Push Playlist
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add samsungtvplus_*.m3u
        git commit -m "🔄 Auto-update SamsungTVPlus root playlists"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
